#!/usr/bin/env bash
# Script that configures Nginx server with a 301 redirect

# Update package list
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Create a simple HTML page with "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html

# Configure 301 redirect for /redirect_me
sed -i '/listen 80 default_server;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
