#!/usr/bin/env bash
# Script that configures Nginx server with a custom 404 page and 301 redirect

# Update package list
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Create a simple HTML page with "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure 301 redirect for /redirect_me
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Configure custom 404 page
sed -i '/server_name _;/a \\terror_page 404 /404.html;\n\\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
